### ISSUE TITLE
Feature request: Ability to easily access multiple notes from a single Duty

### ISSUE THREAD

**Issue by JustMeForFun** [Tischel/NOTED#1]
Hey, I just found your plug-in and absolutely love the potential of this plug-in :D

For a while I've been looking for a way of saving a ton of text macro's. Just to make macro's to explain fights to people but when a Duty has multiple fights it's almost impossible to do since it would take up a ton of space in the games macro menu.

With this plug-in however I can in theory save as many text macro's per Duty as I would like but as it is right now I can only easily access 1 at a time. I would love to be able to easily access multiple notes from a Duty so that I can make separate text macro's for each fight in an Duty. 

So a simple way of browsing through the notes of a Duty would be awesome.

**Comment by Tischel** [comment]
Added keybinds to cycle through notes in v1.1.0.0
