### ISSUE TITLE
Feature Request: Visibility options

### ISSUE THREAD

**Issue by ZohiDev** [Tischel/NOTED#2]
Hello! I'd love to use this plugin more, but having the notes up for the entire fight is pretty distracting for me. Some visibility options for the note would be awesome if possible! Some examples could be:

- Manually Hide (with a - button or something)
- Automatically Hide after X time
- Automatically hide in Combat (my fav!)

**Comment by Tischel** [comment]
Added some visibility options in v1.1.0.0
