### ISSUE TITLE
Support tabs in notes

### ISSUE THREAD

**Issue by SnoFox** [Tischel/NOTED#4]
Hi there,

Thank you for this plugin! It's brilliant!
I'm migrating my duty notes from [NeatNoter](https://github.com/kalilistic/NeatNoter) to NOTED, but all my notes are riddled with tabs due to my note taking style. When pasting them in from NeatNoter, it seems that all the tabs are stripped. Pressing tab myself moves the cursor between the title and the editor.

Is it possible to make it so that tab only acts as a navigation key when not in the main note editor?

Current workarounds: I could write a program to open and modify NeatNoter's database to replace tab characters, but I would still prefer to use tabs over spaces for natural language notes. (The old Tabs vs Spaces argument...)

Thanks,

**Comment by Tischel** [comment]
Fixed in v1.2.1.0, sorry for the delay :P
