### ISSUE TITLE
Make plugin windows resizable

### ISSUE THREAD

**Issue by Uriei** [Tischel/NOTED#5]
As of right now, the plugin windows can't be resized, which for some of them might be manageable, but for others don't.

Main window: 
![image](https://github.com/Tischel/NOTED/assets/6078221/0e2073b2-7653-469f-bdc3-1ecde18cba53)

Job filter selector: 
![image](https://github.com/Tischel/NOTED/assets/6078221/0c250149-aff7-4c2f-b549-e55be5903b05)

the job list is completely cut because of this.

**Comment by Tischel** [comment]
Fixed in v1.2.1.0, sorry for the delay :P
