### ISSUE TITLE
NOTED game crash

### ISSUE THREAD

**Issue by SnoFox** [Tischel/NOTED#7]
Hi there. I've narrowed down a reproducible game crash related to NOTED. I have a note for Containment Bay S1T7 with the text "Stack in center at 60% when BB leaves the arena" (I cannot recall what this note was even for but my poor note taking skills are besides the point)

I changed the text to spell out "percent" instead of using the percent sign and it no longer crashes. Writing out "... 60% percent when" also is fine. However, using the editor while in Containment Bay S1T7 to restore the text to the original crash string (just hitting backspace through "percent"), it immediately crashes when restored to its previous state.

I don't know if it's related, but I've noticed that this plugin has never properly displayed % for me.

NOTED is the only plugin loaded (all others are disabled) and causes the game to crash without an error message from Dalamud nor stacktrace. If you leave it loaded when you log back in, the game insta-crashes since you're still in Containment Bay S1T7 :D

I'm available on Discord under the same name if you want to chat/debug on the XIVLauncher/Dalamud Discord.

[dalamud.log](https://github.com/Tischel/NOTED/files/13691121/dalamud.log)
![Screenshot-ARCTIC-6278-ffxiv_dx11](https://github.com/Tischel/NOTED/assets/37625/dd0c95ac-0a9c-4ea6-baed-99335bb79fef)

**Comment by Tischel** [comment]
Fixed in v1.2.1.0, sorry for the delay :P
